[pytest]
testpaths = tests
python_files = test_*.py
asyncio_mode = auto
asyncio_default_test_loop_scope = session
asyncio_default_fixture_loop_scope = session
addopts = -v -p no:warnings --strict-markers --cov=app --cov-report=term-missing
markers =
    asyncio: marks test as asyncio (select with '-m asyncio')